<?php
/**
 * Copyright 2019 Vipps
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 *    documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 *  and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
/** @var Mage_Adminhtml_Block_Template $this */ ?>
<div class="content-header">

    <table cellspacing="0">
        <tbody><tr>
            <td style="width:50%;">
                <h3 class="icon-head">
                    <?php echo __('Profiling Item #%s', $this->getRequest()->getParam('entity_id')) ?>
                </h3>
            </td>
            <td class="form-buttons">
                <button
                        id="action-back"
                        title="Back"
                        type="button"
                        class="action- scalable back"
                        onclick="location.href='<?php echo $this->getUrl('*/*'); ?>'">
                    <span><?php echo __('Back') ?></span>
                </button>
            </td>
        </tr>
        </tbody>
    </table>
</div>

