<?php
/**
 * Copyright 2019 Vipps
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 *    documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 *  and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */
//@codingStandardsIgnoreFile
/** @var Vipps_Payment_Block_Adminhtml_RequestProfiling_View $this */
$item = $this->getItem();  ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo __('Profiling Item Information'); ?></h4>
    </div>
    <table class="form-list">
        <tbody>
        <tr>
            <td class="label"><?php echo __('Increment Id'); ?></td>
            <td><?= $item->getIncrementId(); ?></td>
        </tr>
        <tr>
            <td class="label"><?= __('Created At'); ?></td>
            <td><?= $item->getCreatedAt(); ?></td>
        </tr>
        <tr>
            <td class="label"><?= __('Request Type'); ?></td>
            <td><?= $item->getRequestType(); ?></td>
        </tr>
        <tr>
            <td class="label"><?= __('Response Code'); ?></td>
            <td><?= $item->getStatusCode(); ?></td>
        </tr>
        <tr>
            <td class="label"><?= __('Request'); ?></td>
            <td><?= $item->getFormattedRequest(); ?></td>
        </tr>
        <tr>
            <td class="label"><?= __('Response'); ?></td>
            <td><?= $item->getFormattedResponse(); ?></td>
        </tr>
        </tbody>

    </table>

</div>

