<?php
/**
 * Copyright 2018 Vipps
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 *  documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 *  the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 *  and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 *  TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL
 *  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 *  CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 *
 */
//@codingStandardsIgnoreFile
/** @var Vipps_Payment_Block_Adminhtml_QuoteMonitoring_Buttons $this */
$vippsQuote = $this->getVippsQuote(); ?>
<div class="content-header">
    <p class="form-buttons">
        <button
                id="action-back"
                title="Back"
                type="button"
                class="action- scalable back"
                onclick="location.href='<?php echo $this->getUrl('*/*'); ?>'">
            <span><?php echo __('Back') ?></span>
        </button>
        <?php if ($this->isRestartVisible()) : ?>
            <button
                    id="action-restart"
                    title type="button"
                    class="action-default primary"
                    onclick="location.href='<?php echo $this->getUrl('*/*/restart', ['entity_id' => $vippsQuote->getEntityId()]); ?>'">
                <span><?php echo __('Restart Processing') ?></span>
            </button>
        <?php endif; ?>
        <?php if ($this->isCancelVisible()) : ?>
            <button
                    id="action-cancel"
                    title type="button"
                    onclick="doCancel()"
                    class="action-scalable action-secondary">
                <span><?php echo __('Cancel') ?></span>
            </button>
        <?php endif; ?>
    </p>
</div>
<script>
    function doCancel() {
        if (confirm("<?php echo __('Are you sure?') ?>")) {
            location.href = '<?php echo $this->getUrl('*/*/cancel', ['entity_id' => $vippsQuote->getEntityId()]); ?>'
        }
    }
</script>

