<?php
/**
 * Copyright 2018 Vipps
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 *  documentation files (the "Software"), to deal in the Software without restriction, including without limitation
 *  the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 *  and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 *  TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL
 *  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 *  CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 *
 */
//@codingStandardsIgnoreFile
/** @var Vipps_Payment_Block_Adminhtml_QuoteMonitoring_View $this */
$vippsQuote = $this->getVippsQuote();
$attempts = $this->getAttempts();  ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo __('Vipps Quote Information'); ?></h4>
    </div>
    <table class="form-list">
        <tbody>
        <tr>
            <td class="label"><?php echo __('Vipps Quote ID'); ?></td>
            <td class="value"><?php echo $vippsQuote->getEntityId(); ?></td>
        </tr>
        <tr>
            <td class="label"><?php echo __('Reserved Order ID'); ?></td>
            <td class="value"><?php echo $vippsQuote->getReservedOrderId(); ?></td>
        </tr>
        <tr>
            <td class="label"><?php echo __('Store ID'); ?></td>
            <td class="value"><?php echo $vippsQuote->getStoreId(); ?></td>
        </tr>
        <tr>
            <td class="label"><?php echo __('Number Of Attempts'); ?></td>
            <td class="value"><?php echo $vippsQuote->getAttempts(); ?></td>
        </tr>
        <tr>
            <td class="label"><?php echo __('Status'); ?></td>
            <td class="value"><?php echo $this->getStatusLabel($vippsQuote->getStatus()) ?>
            </td>
        </tr>
        <tr>
            <td class="label"><?php echo __('Created At'); ?></td>
            <td class="value"><?php echo $this->formatDate($vippsQuote->getCreatedAt()); ?></td>
        </tr>
        <tr>
            <td class="label"><?php echo __('Last Updated At'); ?></td>
            <td class="value"><?php echo $this->formatDate($vippsQuote->getUpdatedAt()); ?></td>
        </tr>
        </tbody>
    </table>


    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo __('Quote Information'); ?></h4>
    </div>
    <?php if ($loadingError = $this->getQuoteLoadingError()) : ?>
        <?php echo $loadingError; ?>
    <?php else : ?>
        <?php $quote = $this->getQuote(); ?>
        <table class="form-list">
            <tbody>
            <tr>
                <td class="label"><?php echo __('Quote ID'); ?></td>
                <td class="value"><?php echo $quote->getId(); ?></td>
            </tr>
            <tr>
                <td class="label"><?php echo __('Store ID'); ?></td>
                <td class="value"><?php echo $quote->getStoreId(); ?></td>
            </tr>
            <tr>
                <td class="label"><?php echo __('Reserved Order ID'); ?></td>
                <td class="value"><?php echo $quote->getReservedOrderId(); ?></td>
            </tr>
            <tr>
                <td class="label"><?php echo __('Customer Email'); ?></td>
                <td class="value"><?php echo $quote->getCustomerEmail(); ?></td>
            </tr>
            <tr>
                <td class="label"><?php echo __('Customer Full Name'); ?></td>
                <td class="value"><?php echo $quote->getCustomerFirstname() . ' ' . $quote->getCustomerLastname(); ?></td>
            </tr>
            <tr>
                <td class="label"><?php echo __('Grand Total'); ?></td>
                <td class="value"><?php echo $this->getPriceHelper()->currencyByStore($quote->getGrandTotal(), $quote->getStoreId()); ?></td>
            </tr>
            <tr>
                <td class="label"><?php echo __('Is Active'); ?></td>
                <td class="value"><?php echo /* @escapeVerified */
                    $quote->getIsActive() ? 'Yes' : 'No'; ?></td>
            </tr>
            <tr>
                <td class="label"><?php echo __('Created At'); ?></td>
                <td class="value"><?php echo $this->formatDate($quote->getCreatedAt()); ?></td>
            </tr>
            <tr>
                <td class="label"><?php echo __('Last Updated At'); ?></td>
                <td class="value"><?php echo $this->formatDate($quote->getUpdatedAt()); ?></td>
            </tr>
            </tbody>
        </table>
    <?php endif; ?>

    <?php if ($attempts->count()) : ?>
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo __('Attempts'); ?></h4>
        </div>
        <table class="form-list">
            <tbody>
            <?php
            /** @var Vipps_Payment_Model_Resource_Quote_Attempt $attempt */
            foreach ($attempts as $attempt) : ?>
                <tr>
                    <td class="label"><?php echo $this->formatDate($attempt->getCreatedAt()); ?></td>
                    <td class="value"><?php echo $attempt->getMessage(); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php else : ?>
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo __('No attempts found.') ?></h4>
        </div>
    <?php endif; ?>
</div>

